name: Artifac CICD
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Build Project
      run: echo "Building Project.." > build.txt

    - name: Upload Project
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: build.txt
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output

      - name: Deploy project
        run: cat build.txt

        

  
