name: commands
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set color
        id: color-selector
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: get color
        env:
          SELECTED_COLOR: ${{steps.color-selector.outputs.SELECTEDCOLOR}}
        run: echo "The selected color is $SELECTED_COLOR"
  
